# Generated by Django 5.2 on 2025-05-01 06:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(default='', help_text='Primary phone number, used for login.', max_length=15, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('fcm_token', models.TextField(blank=True, help_text='Firebase Cloud Messaging device token', null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('bicycle', 'Bicycle'), ('motorcycle', 'Motorcycle'), ('scooter', 'Scooter'), ('car', 'Car')], max_length=15, null=True)),
                ('vehicle_details', models.CharField(blank=True, help_text='License plate, model, etc.', max_length=100, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_available', models.BooleanField(default=False, help_text='Is the agent currently available for deliveries?')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='delivery_agent_profiles/')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this agent should be treated as active.')),
                ('is_approved', models.BooleanField(default=False, help_text='Designates whether the admin has approved this agent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Delivery Agent Profile',
                'verbose_name_plural': 'Delivery Agent Profiles',
            },
        ),
    ]
