# Generated by Django 5.2 on 2025-05-01 06:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(default='', max_length=15, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('fcm_token', models.CharField(blank=True, help_text='Firebase Cloud Messaging device token', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this vendor should be treated as active.')),
                ('is_approved', models.BooleanField(default=False, help_text='Designates whether the admin has approved this vendor.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
            },
        ),
    ]
