# Generated by Django 5.2 on 2025-05-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0003_restaurant_category_fooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_items/'),
        ),
    ]
