from django.urls import path
from .views import (
    CustomerProfileView,
    CustomerProfileUpdateView, 
    CustomerBannersView,       
    CustomerCategoriesView,    
    NearbyRestaurantsView,   
    TopRatedFoodView,        
    RestaurantDetailView,    
    CustomerCartView,        
    CustomerCartAddView,     
    CustomerCartUpdateView,  
    CustomerCartRemoveView,  
    CustomerAddressListView, 
    CustomerAddressAddView,  
    CustomerAddressUpdateView,
    CustomerAddressDeleteView,
    CustomerPlaceOrderView,  
    CustomerOrderListView,   
    CustomerOrderDetailView, 
    CustomerOrderStatusView, 
    CustomerOrderTrackView,  
    CustomerOrderRateView,   
    CustomerCompleteSignupView,
    CategoryListView, 
    RegisterCustomerView # Import the new view
)

urlpatterns = [
    path('complete-signup/', CustomerCompleteSignupView.as_view(), name='customer-complete-signup'), 
    path('profile/', CustomerProfileView.as_view(), name='customer-profile'),
    path('profile/update/', CustomerProfileUpdateView.as_view(), name='customer-profile-update'),
    path('banners/', CustomerBannersView.as_view(), name='customer-banners'),
    path('restaurants/<uuid:restaurant_pk>/categories/', CategoryListView.as_view(), name='customer-categories'),
    path('restaurants/nearby/', NearbyRestaurantsView.as_view(), name='nearby-restaurants'),
    path('food/top-rated/', TopRatedFoodView.as_view(), name='top-rated-food'),
    path('restaurants/<int:pk>/', RestaurantDetailView.as_view(), name='restaurant-detail'),
    path('cart/', CustomerCartView.as_view(), name='customer-cart'),
    path('cart/add/', CustomerCartAddView.as_view(), name='customer-cart-add'),
    path('cart/update/', CustomerCartUpdateView.as_view(), name='customer-cart-update'), 
    path('cart/remove/', CustomerCartRemoveView.as_view(), name='customer-cart-remove'), 
    path('addresses/', CustomerAddressListView.as_view(), name='customer-address-list'),
    path('addresses/add/', CustomerAddressAddView.as_view(), name='customer-address-add'),
    path('addresses/<int:pk>/update/', CustomerAddressUpdateView.as_view(), name='customer-address-update'),
    path('addresses/<int:pk>/delete/', CustomerAddressDeleteView.as_view(), name='customer-address-delete'),
    path('place-order/', CustomerPlaceOrderView.as_view(), name='customer-place-order'),
    path('orders/', CustomerOrderListView.as_view(), name='customer-order-list'),
    path('orders/<int:pk>/', CustomerOrderDetailView.as_view(), name='customer-order-detail'), 
    path('orders/<int:pk>/status/', CustomerOrderStatusView.as_view(), name='customer-order-status'),
    path('orders/<int:pk>/track/', CustomerOrderTrackView.as_view(), name='customer-order-track'),
    path('orders/<int:pk>/rate/', CustomerOrderRateView.as_view(), name='customer-order-rate'),
    path('auth/register/', RegisterCustomerView.as_view(), name='customer-register'),
]
