# Generated by Django 5.2 on 2025-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_agent',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_id_temp',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='menu_item_id_temp',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id_temp',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address_id_temp',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_agent_id_temp',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_id_temp',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item_id_temp',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('user_type', models.CharField(max_length=32)),
                ('fcm_token', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FCM Token',
                'verbose_name_plural': 'FCM Tokens',
                'unique_together': {('user_id', 'user_type')},
            },
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
