# Generated by Django 5.2 on 2025-05-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(help_text='Primary phone number, used for login.', max_length=15, unique=True),
        ),
    ]
